DROP TABLE IF EXISTS casters;
DROPTABLE IF EXISTS spells;

CREATE TABLE casters (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE spells(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(20)
);
