DROP TABLE IF EXISTS casters CASCADE;
DROP TABLE IF EXISTS spells;

CREATE TABLE casters (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE spells (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(20)
);
